name: Zeroconf Py Script
version: 0.0.1
slug: zeroconf_py_script
description: Zeroconf Py Script App
url: "https://github.com/Croydon/ha-apps"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
    path: /app/config
options:
  ZPS_FILE: "/app/config/zeroconf_py_script.py"
schema:
  ZPS_FILE: str
host_network: true
